### ISSUE TITLE
GetSafePathsToAllow creates rules for only last path provided as many times as the number of paths listed

### ISSUE THREAD

**Issue by ssccaavvookk** [microsoft/AaronLocker#21]
When adding paths to CustomizationInputs/GetSafePathsToAllow.ps1 such as:

```
### Windows Defender put their binaries in ProgramData for a while. Comment this back out when they move it back.
"%OSDRIVE%\PROGRAMDATA\MICROSOFT\WINDOWS DEFENDER\*";
"C:\Test1\*";
"D:\Test2\*";
```
The output applocker policy creates 3 FilePathRules for D:\Test2\\*

```
<FilePathRule Id="f57ec424-b91a-4304-8593-9cc076cb1432" Name="Additional allowed path: D:\Test2\*" Description="Allows Everyone to execute from D:\Test2\*" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="D:\Test2\*" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="7a3a4a26-b067-4adb-8cb0-fa5dbacdec09" Name="Additional allowed path: D:\Test2\*" Description="Allows Everyone to execute from D:\Test2\*" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="D:\Test2\*" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="7d5afda0-1373-4358-8505-f9946c350d95" Name="Additional allowed path: D:\Test2\*" Description="Allows Everyone to execute from D:\Test2\*" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="D:\Test2\*" />
      </Conditions>
    </FilePathRule>
```

**Comment by AaronMargosis** [comment]
Where are you seeing that? There should be three: one path rule each for EXE, DLL, and Script collections.

**Comment by ab366s** [comment]
I'm experiencing the same issue. I added multiple lines at the end of the `GetSafePathsToAllow.ps1` file. The end of the file looks like this:

`### Windows Defender put their binaries in ProgramData for a while. Comment this back out when they move it back.`

`"%OSDRIVE%\PROGRAMDATA\MICROSOFT\WINDOWS DEFENDER\*"
"%OSDRIVE%\PROGRAMDATA\MICROSOFT\WINDOWS\PASSWORDEXPIRENOTIFICATION.VBS"
"%OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*"`

If I run the script the output looks good

`PS C:\AaronLocker\CustomizationInputs> .\GetSafePathsToAllow.ps1`

`\\MYDOMAIN.LOCAL\netlogon\*`
`\\MYDOMAIN.LOCAL\sysvol\*`
`%OSDRIVE%\PROGRAMDATA\MICROSOFT\WINDOWS DEFENDER\*`
`%OSDRIVE%\PROGRAMDATA\MICROSOFT\WINDOWS\PASSWORDEXPIRENOTIFICATION.VBS`
`%OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*`

But when you run `Create-Policies.ps1`  path rules are created using only the last line of  `GetSafePathsToAllow.ps1`. In this case only EXE, DLL, and Script rules for `%OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*" ` are created and any previous entries are omitted. 

Actually, it creates multiple entries with the same path


Exe | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
-- | -- | -- | -- | -- | --
Exe | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
Exe | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
Exe | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
Exe | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*

Script | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
-- | -- | -- | -- | -- | --
Script | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
Script | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
Script | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
Script | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*


Dll | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
-- | -- | -- | -- | -- | --
Dll | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
Dll | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
Dll | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*
Dll | AuditOnly | Path | Everyone | Allow | %OSDRIVE%\PROGRAMDATA\SEAGULL\DRIVERS\*

**Comment by jsuther1974** [comment]
Merged fix for this issue.
