### ISSUE TITLE
Unable to add exceptions using GetExeFilesToDenyList.ps1 

### ISSUE THREAD

**Issue by ab366s** [microsoft/AaronLocker#26]
I'm trying to prevent regular users from launching msiexec.exe but when I edit `"C:\AaronLocker\CustomizationInputs\GetExeFilesToDenyList.ps1 "` as shown below 

`# Files used by ransomware`
`"$env:windir\System32\cipher.exe"`
`"$env:windir\System32\msiexec.exe"`

And then re-ran `PS C:\AaronLocker> .\Create-Policies.ps1`

The resulting .xml rules don't include the new exception. 

`[----- Publisher exceptions -----]`

`CIPHER.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; MICROSOFT® WINDOWS® OPERATING SYSTEM`

`INSTALLUTIL.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; MICROSOFT® .NET FRAMEWORK`

`MICROSOFT.WORKFLOW.COMPILER.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; `MICROSOFT® .NET FRAMEWORK`

`MSBUILD.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; MICROSOFT® .NET FRAMEWORK`

`MSHTA.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; INTERNET EXPLORER`

`PRESENTATIONHOST.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; MICROSOFT® WINDOWS® `OPERATING SYSTEM`

`REGASM.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; MICROSOFT® .NET FRAMEWORK`

`REGSVCS.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; MICROSOFT® .NET FRAMEWORK`

`RUNAS.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; MICROSOFT® WINDOWS® OPERATING `SYSTEM`

`WMIC.EXE: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US; MICROSOFT® WINDOWS® OPERATING `SYSTEM`

Please, advice.

**Comment by AaronMargosis** [comment]
Use the -Rescan switch to force it to update what's in ScanResults.

**Comment by AaronMargosis** [comment]
BTW - why do you want to block Msiexec?

**Comment by ab366s** [comment]
That worked!

I'm blocking it because it is categorized in Mitre’s Att&ck Framework as T1218.007 
Defense evasion > Signed binary proxy execution > Msiexec 
This technique has been used by a number of threat actors.

**Comment by AaronMargosis** [comment]
OK. "AaronLocker" already blocks .MSI files that aren't explicitly approved. And blocking Msiexec completely means that users can't run approved MSIs for approved apps (e.g., Zoom/WebEx). I don't know whether Office still does this, but it used to run an MSI on a user's first run of an Office app to complete the user portion of the installation.

**Comment by ab366s** [comment]
I agree. I tested it and it certainly brakes things. This is not a good idea. 

Thanks for your help!
