### ISSUE TITLE
Unexpected Allow in WDAC Deny Rules from createpolicy

### ISSUE THREAD

**Issue by bryan-osisoft** [microsoft/AaronLocker#28]
<FileRules>
    <Allow ID="ID_ALLOW_A_1_0" FriendlyName="" FileName="*" />
    <Allow ID="ID_ALLOW_A_2_0" FriendlyName="" FileName="*" />
    <FileAttrib ID="ID_FILEATTRIB_F_5_1" FriendlyName="C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe FileAttribute" FileName="InstallUtil.exe" MinimumFileVersion="4.8.4084.0" />
    <FileAttrib ID="ID_FILEATTRIB_F_7_1" FriendlyName="C:\Windows\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe FileAttribute" FileName="RegAsm.exe" MinimumFileVersion="4.8.4084.0" />
    <FileAttrib ID="ID_FILEATTRIB_F_9_1" FriendlyName="C:\Windows\Microsoft.NET\Framework\v4.0.30319\RegSvcs.exe FileAttribute" FileName="RegSvcs.exe" MinimumFileVersion="4.8.4084.0" />
    <FileAttrib ID="ID_FILEATTRIB_F_B_1" FriendlyName="C:\Windows\Microsoft.NET\assembly\GAC_32\MSBuild\v4.0_4.0.0.0__b03f5f7f11d50a3a\MSBuild.exe FileAttribute" FileName="MSBuild.exe" MinimumFileVersion="4.8.4084.0" />
    <FileAttrib ID="ID_FILEATTRIB_F_D_1" FriendlyName="C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.Workflow.Compiler\v4.0_4.0.0.0__31bf3856ad364e35\Microsoft.Workflow.Compiler.exe FileAttribute" FileName="Microsoft.Workflow.Compiler.exe" MinimumFileVersion="4.8.4084.0" />
    <FileAttrib ID="ID_FILEATTRIB_F_11_1" FriendlyName="C:\Windows\System32\wbem\WMIC.exe FileAttribute" FileName="wmic.exe" MinimumFileVersion="10.0.19041.1" />
    <FileAttrib ID="ID_FILEATTRIB_F_F_1" FriendlyName="C:\Windows\System32\mshta.exe FileAttribute" FileName="MSHTA.EXE" MinimumFileVersion="11.0.19041.1" />
    <FileAttrib ID="ID_FILEATTRIB_F_10_1" FriendlyName="C:\Windows\System32\PresentationHost.exe FileAttribute" FileName="PresentationHost.exe" MinimumFileVersion="10.0.19041.1" />
    <FileAttrib ID="ID_FILEATTRIB_F_13_1" FriendlyName="C:\Windows\System32\cipher.exe FileAttribute" FileName="CIPHER.EXE" MinimumFileVersion="10.0.19041.1" />
    <FileAttrib ID="ID_FILEATTRIB_F_14_1" FriendlyName="C:\Windows\System32\runas.exe FileAttribute" FileName="RUNAS.EXE" MinimumFileVersion="10.0.19041.1" />
  </FileRules>

**Comment by Wh00T** [comment]
Some additional information:
Two Allow rules are part of both Deny policy files:
WDACRules-20210122-0524-Deny-Audit.xml
WDACRules-20210122-0524-Deny-Enforce.xml

    <Allow ID="ID_ALLOW_A_1_0" FriendlyName="" FileName="*" />
    <Allow ID="ID_ALLOW_A_2_0" FriendlyName="" FileName="*" />

![image](https://user-images.githubusercontent.com/1562582/105446531-93c32900-5c72-11eb-9808-69bbebf8852a.png)

**Comment by jsuther1974** [comment]
This is by design. The policy is "Allow everything except these specific things". Without the Allow * rules, then the policy would *implicitly* block everything and *explicitly* block a few things, but allow nothing.
